apiVersion: v1
kind: Service
metadata:
  name: appguard-book-page
  labels:
    app: appguard-book-page
    example.com/zone: external
    example.com/classification: public
spec:
  ports:
  - port: 30010
    name: http
  selector:
    app: appguard-book-page
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appguard-book-page
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: appguard-book-page
        version: v1
    spec:
      containers:
      - name: appguard-book-page
        image: appguard/book_page:v0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 30010
          hostPort: 30010
---
